name: Build iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --release